name: musify
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.5.3

environment:
  sdk: ">= 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  device_info_plus: ^11.1.1
  permission_handler: ^11.3.1
  audio_service: ^0.18.15
  audio_video_progress_bar: ^2.0.3
  #https://pub.flutter-io.cn/packages/just_audio_mpv

  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  window_manager: ^0.4.2
  dio: ^5.7.0
  crypto: ^3.0.5
  sqflite: ^2.3.3+2
  sqflite_common_ffi: ^2.3.4
  path: ^1.9.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  flutter_lyric: ^2.0.4+6
  share_plus: ^10.0.2
  get: ^4.6.6
  shared_preferences: ^2.3.3
  loading_animation_widget: ^1.3.0
  transparent_image: ^2.0.1
  event_bus: ^2.0.1
  toastification: ^2.3.0
  json_annotation: ^4.9.0
  modal_bottom_sheet: ^3.0.0
  sleek_circular_slider: ^2.0.1
  flutter_svg: ^2.0.15
  infinite_scroll_pagination: ^4.1.0
  popover: ^0.3.1
  logger: ^2.5.0
  rxdart: ^0.28.0
  path_provider: ^2.1.5
  template_expressions: ^3.3.0+2
  flutter_screenutil: ^5.9.3
  toggle_switch: ^2.3.0
  flutter_xlider: ^3.5.0
  carousel_slider: ^5.0.0
  palette_generator: ^0.3.3+5
  flutter_smart_dialog: ^4.9.8+5

dev_dependencies:
  dio_mock_interceptor: ^2.1.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/server_logo/
    - mock/
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf

flutter_intl:
  enabled: true

jsonToDart:
  engine: json_serializable
  outputFolder: lib/models #default: lib/
  # typeChecking: true #default: undefined (Select from picker)
  nullValueDataType: String #default: dynamic
  nullSafety: true #default: false
  # copyWithMethod: true #default: false
  # fromListMethod: true #default: false
  # mergeArrayApproach: false #default: true
  package:
    package:json_annotation/json_annotation.dart

    #default: false,
    #if true, value = (json[key] as num).toInt() or value = (_data[key] as num).toDouble()
    #if false, value = json[key]
    #if "ask", selection popup will apear before parse json
  checkNumberAsNum: true # true, false, "ask"
