// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'nd_song.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

NdSong _$NdSongFromJson(Map<String, dynamic> json) => NdSong(
      playCount: (json['playCount'] as num?)?.toInt(),
      playDate: json['playDate'] as String?,
      rating: (json['rating'] as num?)?.toInt(),
      starred: json['starred'] as bool?,
      starredAt: json['starredAt'] as String?,
      bookmarkPosition: (json['bookmarkPosition'] as num?)?.toInt(),
      id: json['id'] as String?,
      path: json['path'] as String?,
      title: json['title'] as String?,
      album: json['album'] as String?,
      artistId: json['artistId'] as String?,
      artist: json['artist'] as String?,
      albumArtistId: json['albumArtistId'] as String?,
      albumArtist: json['albumArtist'] as String?,
      albumId: json['albumId'] as String?,
      hasCoverArt: json['hasCoverArt'] as bool?,
      trackNumber: (json['trackNumber'] as num?)?.toInt(),
      discNumber: (json['discNumber'] as num?)?.toInt(),
      year: (json['year'] as num?)?.toInt(),
      originalYear: (json['originalYear'] as num?)?.toInt(),
      releaseYear: (json['releaseYear'] as num?)?.toInt(),
      size: (json['size'] as num?)?.toInt(),
      suffix: json['suffix'] as String?,
      duration: (json['duration'] as num?)?.toDouble(),
      bitRate: (json['bitRate'] as num?)?.toInt(),
      channels: (json['channels'] as num?)?.toInt(),
      genre: json['genre'] as String?,
      genres: json['genres'] as List<dynamic>?,
      fullText: json['fullText'] as String?,
      orderTitle: json['orderTitle'] as String?,
      orderAlbumName: json['orderAlbumName'] as String?,
      orderArtistName: json['orderArtistName'] as String?,
      orderAlbumArtistName: json['orderAlbumArtistName'] as String?,
      compilation: json['compilation'] as bool?,
      lyrics: json['lyrics'] as String?,
      rgAlbumGain: (json['rgAlbumGain'] as num?)?.toInt(),
      rgAlbumPeak: (json['rgAlbumPeak'] as num?)?.toInt(),
      rgTrackGain: (json['rgTrackGain'] as num?)?.toInt(),
      rgTrackPeak: (json['rgTrackPeak'] as num?)?.toInt(),
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
    );

Map<String, dynamic> _$NdSongToJson(NdSong instance) => <String, dynamic>{
      'playCount': instance.playCount,
      'playDate': instance.playDate,
      'rating': instance.rating,
      'starred': instance.starred,
      'starredAt': instance.starredAt,
      'bookmarkPosition': instance.bookmarkPosition,
      'id': instance.id,
      'path': instance.path,
      'title': instance.title,
      'album': instance.album,
      'artistId': instance.artistId,
      'artist': instance.artist,
      'albumArtistId': instance.albumArtistId,
      'albumArtist': instance.albumArtist,
      'albumId': instance.albumId,
      'hasCoverArt': instance.hasCoverArt,
      'trackNumber': instance.trackNumber,
      'discNumber': instance.discNumber,
      'year': instance.year,
      'originalYear': instance.originalYear,
      'releaseYear': instance.releaseYear,
      'size': instance.size,
      'suffix': instance.suffix,
      'duration': instance.duration,
      'bitRate': instance.bitRate,
      'channels': instance.channels,
      'genre': instance.genre,
      'genres': instance.genres,
      'fullText': instance.fullText,
      'orderTitle': instance.orderTitle,
      'orderAlbumName': instance.orderAlbumName,
      'orderArtistName': instance.orderArtistName,
      'orderAlbumArtistName': instance.orderAlbumArtistName,
      'compilation': instance.compilation,
      'lyrics': instance.lyrics,
      'rgAlbumGain': instance.rgAlbumGain,
      'rgAlbumPeak': instance.rgAlbumPeak,
      'rgTrackGain': instance.rgTrackGain,
      'rgTrackPeak': instance.rgTrackPeak,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
    };
