name: Test, Build and Release apk
on:
  push:
    branches:
      - "master"
      - "releases/**"
    tags:
      - v**

env:
  FLUTTER_VERSION: 3.24.3

jobs:
  build-andriod-apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.12.0
        with:
          cache: true
          cache-key: ubuntu-latest-flutter-${{ hashFiles('**/pubspec.yaml') }}
          flutter-version: ${{ env.FLUTTER_VERSION  }}
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
          check-latest: true
      - name: Install dependencies
        run: |
          flutter pub get
          flutter test
          flutter build apk --obfuscate --split-debug-info=./

      - name: Push APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.TOKEN }}
  # build-ios:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"
  #         cache: true
  #         architecture: x64

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Build iOS
  #       run: flutter build ios --release --no-codesign
